services:
  php:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/sherob.conf:/etc/apache2/sites-enabled/sherob.conf

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sherob

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql